# Generated by Django 3.2.9 on 2022-01-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=10)),
            ],
        ),
    ]
