# Generated by Django 4.0.2 on 2023-08-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.PositiveIntegerField(choices=[(11, 'Electronic'), (12, 'Clothing'), (13, 'Crockery'), (14, 'Toys'), (15, 'Grocery'), (16, 'Furniture'), (17, 'Jewellery')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(),
        ),
    ]
