# Generated by Django 4.0.2 on 2023-08-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_product_subcategory_alter_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
