# Generated by Django 4.0.2 on 2023-08-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=500)),
                ('category', models.PositiveIntegerField(choices=[(11, 'Electronic'), (12, 'Clothing'), (13, 'Crockery'), (14, 'Toys'), (15, 'Grocery'), (16, 'Furniture'), (17, 'Jewellery')])),
                ('price', models.IntegerField(default=0)),
                ('desc', models.TextField()),
                ('publish_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
